#! /bin/bash

#define icons for workspaces 1-9
#icontheme=$(geticons -U)
icontheme=$(grep "gtk-icon-theme-name" "$HOME"/.config/gtk-3.0/settings.ini | cut --delimiter="=" -f 2)

workspaces() {
if [[ ${1:0:14} == "activewindow>>" ]]; then #set focused workspace
    string=${1:14}
    class="${string/,*/}"
    export title=${string/,/ \| }
    [[ $title == " | " ]] && unset title
    export iconpath=$(geticons "$class" -s 24 -c 1 -t "$icontheme" | head -n 1)
    if [ -z "$iconpath" ]; then
        echo "cannot find icon for $class" >> ~/.cache/appname.log
        $class = "default-application"
        export iconpath=$(geticons "$class" -s 24 -c 1 -t "$icontheme" | head -n 1)

    fi
    echo "ICONPATH: $iconpath ICONTHEME $icontheme" >> ~/.cache/appname.log
fi
}

module() {
#output eww widget
echo 	"(box \
                :orientation \"h\" \
                :halign \"start\" \
                :space-evenly false \
                (image \
                    :class \"app-icon\" \
                    :path \"$iconpath\" \
                    :image-width \"36\") \
                (label \
                    :class \"app-name\" \
                    :limit-width \"35\" \
                    :text \"$title\" \
                    :tooltip \"$title\"))"
}

socat -u UNIX-CONNECT:/tmp/hypr/"$HYPRLAND_INSTANCE_SIGNATURE"/.socket2.sock - | while read -r event; do 
workspaces "$event"
module
done
