#!/bin/bash
# Get Volume

get_volume() {
    vol=$(wpctl get-volume @DEFAULT_SOURCE@ | perl -pe 'chomp' | grep -Eo "[0-9\.].*+"  )
    if [[ $vol =~ "MUTED" ]]; then
        echo -n "Mute"
    else
        whole=$(echo "$vol * 100"| bc )
        vol=$(LC_ALL=C printf '%.0f' "$whole")
        echo $vol
    fi
	#if [[ "$status" == "on" ]]; then
	#	volume=`amixer get Master | tail -n1 | awk -F ' ' '{print $5}' | tr -d '[%]'`
	#	echo "$volume"
	#else
	#	echo "Mute"
	#fi
}

# Get icons
get_icon() {
	vol="$(get_volume)"
	current="${vol%%%}"
	status=`amixer get Master | tail -n1 | grep -wo 'on'`

	if [[ "$status" == "on" ]]; then
		if [[ "$current" -eq "0" ]]; then
			echo "ﱝ"
		elif [[ ("$current" -ge "0") && ("$current" -le "30") ]]; then
			echo "奄"
		elif [[ ("$current" -ge "30") && ("$current" -le "60") ]]; then
			echo "奔"
		elif [[ ("$current" -ge "60") && ("$current" -le "100") ]]; then
			echo "墳"
		fi
	else
		echo "ﱝ"
	fi
}

# Increase Volume
inc_volume() {
     wpctl set-volume -l 1.5 @DEFAULT_AUDIO_SINK@ 5%+
}

# Decrease Volume
dec_volume() {
    wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-
}

# Toggle Mute
toggle_mute() {
    wpctl set-mute @DEFAULT_SOURCE@ toggle
}

# Execute accordingly
if [[ "$1" == "--get" ]]; then
	get_volume
elif [[ "$1" == "--icon" ]]; then
	get_icon
elif [[ "$1" == "--inc" ]]; then
	inc_volume
elif [[ "$1" == "--dec" ]]; then
	dec_volume
elif [[ "$1" == "--toggle" ]]; then
	toggle_mute
else
	get_volume
fi
