#!/bin/bash

## Files and cmd
EWW="eww ${EWW_DEBUG_FLAG} -c $HOME/.config/eww/"

## Run eww daemon if not running already
if [[ ! $(pidof eww) ]]; then
    ${EWW} daemon
    sleep 1
fi

## Open widgets
NB_MONITORS=($(hyprctl monitors -j | jq -r '.[] | .id'))
for i in "${!NB_MONITORS[@]}"; do
    ${EWW} open bar$i
    [[ $i == 0 ]] && ${EWW} open-many sidebar notifications
    #[[ $i == 0 ]] && ${EWW} open-many notifications
done
